In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
url = 'E:\\Dessertation\\desertion_dkit_msc_2022_sep\\output.csv'
# d parser df:=lambda x: pd.datetime.strptime(x,'gy-8m-gd gI-Sp")
df = pd.read_csv(url, index_col = 'year', parse_dates=True, infer_datetime_format=True)
# df = pd.read_csv(url)
# df['year'] = pd.to_datetime(df['year'], format='%Y%', errors='ignore')
# # Converting the index as date
# df.index = pd.to_datetime(df.index)

# df = df.index.year
# df = df.set_index('year')

# # Converting the index as date
# df.index = pd.to_datetime(df.index)
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 13276 entries, 1985-01-01 to 2015-01-01
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   country               13276 non-null  object
 1   sex                   13276 non-null  object
 2   age                   13276 non-null  object
 3   suicides              13276 non-null  int64
 4   population            13276 non-null  int64
 5   sucid_in_hundredk     13276 non-null  float64
 6   country-year          13276 non-null  object
 7   yearly_gdp            13276 non-null  float64
 8   gdp_per_capita        13276 non-null  int64
 9   generation            13276 non-null  object
 10  suicides.1            13276 non-null  float64
 11  internetusers         13276 non-null  float64
 12  expenses              13276 non-null  float64
 13  employeecompensation  13276 non-null  float64
 14  unemployment          13276 non-null  float64
 15  physician_price       13276 non-null  float64
 16  laborforcetotal       13276 non-null  float64
 17  lifeexpectancy        13276 non-null  float64
 18  mobilesubscriptions   13276 non-null  float64
 19  refugees              13276 non-null  float64
 20  selfemployed          13276 non-null  float64
 21  electricityacess      13276 non-null  float64
 22  continent             13276 non-null  object
 23  country_code          13276 non-null  object
 24  mobilesubscription    13276 non-null  float64
dtypes: float64(15), int64(3), object(7)
memory usage: 2.6+ MB

In [3]:
russia = df[(df.country == 'Russian Federation')]
russia.head()

,country,sex,age,suicides,population,sucid_in_hundredk,country-year,yearly_gdp,gdp_per_capita,generation,...,physician_price,laborforcetotal,lifeexpectancy,mobilesubscriptions,refugees,selfemployed,electricityacess,continent,country_code,mobilesubscription
year,,,,,,,,,,,,,,,,,,,,,
1989-01-01,Russian Federation,male,75+ years,1393,1349100,103.25,Russian Federation1989,5.065000e+11,3740,G.I. Generation,...,0.2384,1.077831e+07,50.156848,0.009469,10732.386792,2.157578,57.6,Europe,RUS,0.009469
1989-01-01,Russian Federation,male,35-54 years,12030,18058500,66.62,Russian Federation1989,5.065000e+11,3740,Silent,...,0.2384,1.077831e+07,50.156848,0.009469,10732.386792,2.157578,57.6,Europe,RUS,0.009469
1989-01-01,Russian Federation,male,55-74 years,6250,9383700,66.60,Russian Federation1989,5.065000e+11,3740,G.I. Generation,...,0.2384,1.077831e+07,50.156848,0.009469,10732.386792,2.157578,57.6,Europe,RUS,0.009469
1989-01-01,Russian Federation,male,25-34 years,6856,12748800,53.78,Russian Federation1989,5.065000e+11,3740,Boomers,...,0.2384,1.077831e+07,50.156848,0.009469,10732.386792,2.157578,57.6,Europe,RUS,0.009469
1989-01-01,Russian Federation,female,75+ years,1677,4738100,35.39,Russian Federation1989,5.065000e+11,3740,G.I. Generation,...,0.2384,1.077831e+07,50.156848,0.009469,10732.386792,2.157578,57.6,Europe,RUS,0.009469

In [4]:
columns = ['sucid_in_hundredk']
russia = pd.DataFrame(russia, columns=columns)
russia.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 324 entries, 1989-01-01 to 2015-01-01
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sucid_in_hundredk  324 non-null    float64
dtypes: float64(1)
memory usage: 5.1 KB

In [5]:
print(russia.shift(3))

            sucid_in_hundredk
year
1989-01-01                NaN
1989-01-01                NaN
1989-01-01                NaN
1989-01-01             103.25
1989-01-01              66.62
...                       ...
2015-01-01              24.11
2015-01-01              13.70
2015-01-01               6.50
2015-01-01               5.95
2015-01-01               5.81

[324 rows x 1 columns]